### ISSUE TITLE
Wrong CSS File

### ISSUE THREAD

**Issue by Eltii** [dlecina/StayPuft#12] opened 2015-08-26 13:55 UTC
I think your using the wrong "screen.css" file in the version on github .. it doesnt work, i took the file directly from your website and it worked normally .

**Comment by dlecina** [comment] 2015-09-01 12:42
That's odd. I just checked both versions of the file for differences and there were none. I'll give it another look next time I update the theme.

**Comment by Eltii** [comment] 2015-09-01 22:07
this is very weird ... its a file inside the zip i upload .. but its another when i install it :|

the one that i find when i install 
has 13 sections

![screenshot from 2015-09-02 00 07 03](https://cloud.githubusercontent.com/assets/7010334/9618406/911ebb38-5106-11e5-9e0a-fd61a2d64ad4.png)

**Comment by Eltii** [comment] 2015-09-01 22:17
fixed .. ghost was passing some wrong version of the css .. im not even sure where did it get it from
fixed it by changing 
`<link rel="stylesheet" type="text/css" href="{{asset "css/screen.css"}}" />`
to
`<link rel="stylesheet" type="text/css" href=/"asset/css/screen.css" />`

ghost was passing `screen.css?v=5ad39.........` insted of screen.css and i have no idea where did that come from :|

**Comment by dlecina** [comment] 2015-10-12 23:04
Cannot reproduce. I'll close this for now.

**Closed by dlecina** 2015-10-12 23:04 UTC
