### ISSUE TITLE
is there a way to display posts as collapsed ?

### ISSUE THREAD

**Issue by cancobanoglu** [dlecina/StayPuft#18] opened 2016-09-24 21:24 UTC
hi, 

i wasn't sure to ask it here. But i really want to show my posts as collapsed but all are displaying opened. I think that it would be hard to find a specific post among them. By the way, i love this theme some much :)

**Comment by dlecina** [comment] 2016-09-25 10:13
Closing this is a duplicate of #2

**Closed by dlecina** 2016-09-25 10:13 UTC
